In [5]:
import pandas as pd
import pandera as pa

ModuleNotFoundError: No module named 'pandera'

In [2]:
tabela = pd.read_csv('ocorrencia.csv', sep=';', parse_dates=['ocorrencia_dia'], dayfirst=True)
tabela.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3
2,45333,45333,ACIDENTE,VIAM�O,RS,****,2012-01-06,13:00:00,0
3,45401,45401,ACIDENTE,S�O SEBASTI�O,SP,****,2012-01-06,17:00:00,0
4,45407,45407,ACIDENTE,S�O SEP�,RS,****,2012-01-06,16:30:00,0
5,52243,52243,INCIDENTE,UBATUBA,SP,****,2012-01-06,14:30:00,0
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
7,45334,45334,INCIDENTE,BEL�M,PA,SBBE,2012-01-08,19:12:00,0
8,45391,45391,ACIDENTE,CONCEI��O DAS ALAGOAS,MG,****,2012-01-08,16:00:00,0
9,52244,52244,INCIDENTE,UBERL�NDIA,MG,SBUL,2012-01-08,22:13:00,0

In [4]:
schema = pa.DataFrameSchema (
    columns = {
        "codigo_ocorrencia":pa.Column(pa.Int)
    }
)

NameError: name 'pa' is not defined

In [ ]:
schema.validate(tabela)

In [ ]:
tabela.dtypes